version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: "/"
    allow:
      - dependency-type: all
    schedule:
      interval: "weekly"
    groups:
      python-packages:
        patterns:
          - "*"
