name: "Pull Request Labeler"

on:  # yamllint disable-line rule:truthy
  pull_request_target:
    branches:
      - 'master'
jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5  # yamllint disable-line rule:indentation
